apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: raju-test-eks
  region: us-east-1
  version: "1.23"

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-0245f71f5dfac67cb }
      us-east-1b: { id: subnet-0abb070267ad6ffc1 }
    public:
      us-east-1a: { id: subnet-0cfb3bb84e787065e }
      us-east-1b: { id: subnet-01bae7787c84f740a }

managedNodeGroups:
  - name: ng-2
    instanceType: t3.medium
    desiredCapacity: 1
    ssh: # use existing EC2 key
      publicKeyName: raju
    subnets:
      - subnet-0245f71f5dfac67cb
      - subnet-0abb070267ad6ffc1

























































managedNodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    ssh: # import public key from file
      publicKeyPath: ~/.ssh/id_rsa_tests.pub
  - name: ng-2
    instanceType: m5.large
    desiredCapacity: 1
    ssh: # use existing EC2 key
      publicKeyName: ec2_dev_key